PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX dbc: <http://dbpedia.org/resource/Category:>

SELECT ?country (STR(?population) AS ?population_str)
WHERE {
  ?country rdf:type dbo:Country ;
           dbo:populationTotal ?population ;
           dcterms:subject dbc:Eastern_European_countries .
  FILTER (?country != <http://dbpedia.org/resource/Azerbaijan> && 
          ?country != <http://dbpedia.org/resource/Kazakhstan>)
  # Ensure only the first population value is used
  FILTER NOT EXISTS { ?country dbo:populationTotal ?otherPopulation. FILTER (?otherPopulation != ?population) }
}
ORDER BY DESC(xsd:integer(?population))
